name: recipe
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_riverpod: ^0.14.0+3
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^0.14.0+5

  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  firebase_storage: ^10.0.2

  image_picker: ^0.8.3+3
  file_picker: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
