name: recipe
description: A new Flutter project.
version: 1.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation:
  json_annotation: ^4.4.0

  flutter_lints: ^2.0.1
  pedantic_mono: ^1.19.2

  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1

  firebase_core: ^2.1.1
  firebase_core_platform_interface: ^4.5.2
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^4.0.0
  firebase_storage: ^11.0.4

  package_info_plus: ^3.0.1
  flutter_email_sender: ^5.1.0
  webview_flutter: ^3.0.4
  in_app_review: ^2.0.4
  sign_button: ^2.0.2
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^2.0.0
  uuid: ^3.0.5
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.1
  form_validator: ^1.0.2
  settings_ui: ^2.0.2
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.2
  permission_handler: ^10.0.0

  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flex_color_scheme: ^6.0.1
  dropdown_button2: ^1.6.3
  persistent_bottom_nav_bar_v2: ^4.2.4
  adaptive_action_sheet: ^2.0.1
  badges: ^2.0.2
  fraction: ^4.0.1
  device_preview: ^1.1.0

  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.0

  flutter_test:
    sdk: flutter

  freezed:
  json_serializable:
  hive_generator: ^2.0.0
  flutter_tree: ^2.0.3
  monarch: ^3.0.0-pre.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/introductions/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon-prod.png"

flutter_native_splash:
  color: "#fafafa"
  image: "lib/assets/splash_light.png"
  color_dark: "#424242"
  image_dark: "lib/assets/splash_dark.png"
