name: recipe
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  freezed_annotation:
  json_annotation: ^4.4.0

  flutter:
    sdk: flutter

  riverpod: ^1.0.2
  hooks_riverpod: ^1.0.2

  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^3.3.0
  firebase_storage: ^10.0.2

  sign_button: ^2.0.2
  hawk_fab_menu: ^1.1.2
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  uuid: ^3.0.5
  image_picker: ^0.8.3+3
  image_cropper: ^1.5.1
  form_validator: ^1.0.2
  settings_ui: ^2.0.2
  flutter_easyloading: ^3.0.3

  google_fonts: ^2.3.1
  flex_color_scheme: ^4.2.0
  snapping_sheet: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  adaptive_action_sheet: ^2.0.1
  modal_bottom_sheet: ^2.0.1
  badges: ^2.0.2
  fraction: ^4.0.1

  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:
  hive_generator: ^1.1.2
  flutter_tree: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - images/
